### PR TITLE
Move sample app to use SPM instead of Carthage

### PR DESCRIPTION
**Pull request by shali3**
The idea is to reduce friction for users trying to experiment with the sample app.
This was done by:
- Removing Cartfile(s) and Carthage integration in the Xcode project
- Adding Rx and SnapKit with SPM
- Set DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC=YES for Pluginized example.
  Context: https://forums.swift.org/t/adding-a-package-to-two-targets-in-one-projects-results-in-an-error/35007

### CODE REVIEW

**Comment by shali3** [comment]
Hi @rudro @neakor,
As part of a research for DI frameworks to my company I checked out your library and had some trouble running the Sample app due to Carthage (I'm used to use cocoapods). I eventually figured it out, but it wasn't a great experience.
I created this PR to migrate your sample apps to use SPM to lower the friction of setting it up for testing (native in Xcode).

I had to tweak travis configuration to make sure CI works as well, and now it runs smoothly :)
I hope you like this change and approve it so other engineers trying to get a quick demo will be able to do so quickly :)

Thanks,
ShaLi

**Comment by shali3** [comment]
Hi There, I would love to get some feedback about this :)

**Review by rudro — COMMENTED** [review]
Looks good.  Thanks for doing this

**Review by rudro — APPROVED** [review]
thanks for this

**Pull request merged**
