### PR TITLE
Update Generator's SwiftSyntax version

### PR DESCRIPTION
**Pull request by MarcelStarczyk**

### CODE REVIEW

**Comment by strawb3rryx7** [comment]
@rudro

**Comment by rudro** [comment]
Ah, this is tricky. With a codebase our size, it takes us a bit to move to the new versions as they come out.

We are, unfortunately, in the middle of our move to Xcode 12.x, and as soon as that's done, I'd be happy to merge this.

**Comment by strawb3rryx7** [comment]
> Ah, this is tricky. With a codebase our size, it takes us a bit to move to the new versions as they come out.
> 
> We are, unfortunately, in the middle of our move to Xcode 12.x, and as soon as that's done, I'd be happy to merge this.

Got it, So, Is there any workarounds **not to interrupt** our development process?

**Comment by strawb3rryx7** [comment]
> Ah, this is tricky. With a codebase our size, it takes us a bit to move to the new versions as they come out.
> 
> We are, unfortunately, in the middle of our move to Xcode 12.x, and as soon as that's done, I'd be happy to merge this.

Got it, So, Is there any workarounds **not to interrupt** our development process?

**Comment by tianskylan** [comment]
I had done this in #380. Closing this now.
Thanks for submitting the PR though!

**Pull request closed without merging**
