### PR TITLE
Add dynamicMemberLookup to Component for direct dependency access

### PR DESCRIPTION
**Pull request by ebgraham**
Needle codebases will end up with dependencies coming from both the component and the component's dependency protocol:

```
let interactor = LoggedInInteractor(loggedInStream: component.dependency.loggedInStream,
                                    networkClient: component.networkClient,
                                    appUpdater: component.dependency.appUpdater,
                                    modelProvider: component.modelProvider,
                                    modelRefresher: component.dependency.modelRefresher)
```
We can leverage Swift 5.1's dynamicMemberLookup keypath support to make property access consistent for all component dependencies and avoid developers the slight pain of typing `component.` or `component.dependency.` to find their dependency, and unnecessary updates during dependency refactor.
```
let interactor = LoggedInInteractor(loggedInStream: component.loggedInStream,
                                    networkClient: component.networkClient,
                                    appUpdater: component.appUpdater,
                                    modelProvider: component.modelProvider,
                                    modelRefresher: component.modelRefresher)
```

### CODE REVIEW

**Comment by vivekvichare** [comment]
We can wait for @rudro to green-light this (unless this is super urgent).

Apart from that, this addition looks like a great addition to me! Makes code cleaner without compromising on the compile time safety that needle pushes for. Thanks for adding this @ebgraham  .

**Comment by vivekvichare** [comment]
This also requires us to upgrade the Swift version to 5.1. That's what's breaking the current tests. Once again @rudro would be the right person to make that call. But it would be good to get the required changes into this diff and verify that the existing unit tests pass.

**Comment by rudro** [comment]
@ebgraham this looks ok to me, but we can't merge with CI being red.  As Vivek noted, we need to make the Swift 5.1 switch first.  Would you like to add that change to this PR or prefer we do that separately and land that first?

**Comment by rudro** [comment]
Landed this in #340 (along with some versions updates and such)

**Pull request closed without merging**
